# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userUnit', '0006_auto_20160516_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.TextField()),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('hasCover', models.BooleanField(default=False)),
                ('image', models.TextField(null=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('disliker', models.ManyToManyField(related_name='dislike', to='userUnit.CdUser')),
                ('liker', models.ManyToManyField(related_name='like', to='userUnit.CdUser')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duanOwner', to='userUnit.CdUser')),
            ],
        ),
        migrations.CreateModel(
            name='DuanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('duan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudUnit.Duan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userUnit.CdUser')),
            ],
        ),
        migrations.CreateModel(
            name='DuanLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10)),
                ('ofDuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='cloudUnit.Duan')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ofDuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cloudUnit.Duan'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOwner', to='userUnit.CdUser'),
        ),
    ]
