# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userUnit', '0002_cduser_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=200)),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='uploadFiles/Duan/%Y/%m/%d')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duanOwner', to='userUnit.CdUser')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='ofDuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofDuan', to='cloudUnit.Duan'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentOwner', to='userUnit.CdUser'),
        ),
    ]
