# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duan',
            name='content',
            field=models.TextField(),
        ),
    ]
