# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0002_auto_20160515_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuanLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=10)),
                ('ofDuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label', to='cloudUnit.Duan')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='ofDuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='cloudUnit.Duan'),
        ),
    ]
