# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userUnit', '0006_auto_20160516_1755'),
        ('cloudUnit', '0003_auto_20160516_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='duan',
            name='disliker',
            field=models.ManyToManyField(related_name='dislike', to='userUnit.CdUser'),
        ),
        migrations.AddField(
            model_name='duan',
            name='liker',
            field=models.ManyToManyField(related_name='like', to='userUnit.CdUser'),
        ),
    ]
