# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0003_duan_hascover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duan',
            options={'ordering': ['-publishTime']},
        ),
        migrations.AlterModelOptions(
            name='duanhistory',
            options={'ordering': ['-time']},
        ),
    ]
