# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0004_auto_20160516_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duan',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
