# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userUnit', '0006_auto_20160516_1755'),
        ('cloudUnit', '0005_auto_20160516_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuanHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='duan',
            name='disliker',
            field=models.ManyToManyField(null=True, related_name='dislike', to='userUnit.CdUser'),
        ),
        migrations.AlterField(
            model_name='duan',
            name='liker',
            field=models.ManyToManyField(null=True, related_name='like', to='userUnit.CdUser'),
        ),
        migrations.AddField(
            model_name='duanhistory',
            name='duan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudUnit.Duan'),
        ),
        migrations.AddField(
            model_name='duanhistory',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userUnit.CdUser'),
        ),
    ]
