# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userUnit', '0006_auto_20160516_1755'),
        ('cloudUnit', '0005_duan_purecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='duan',
            name='collector',
            field=models.ManyToManyField(related_name='collect', to='userUnit.CdUser'),
        ),
    ]
