# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0006_auto_20160517_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duan',
            name='disliker',
            field=models.ManyToManyField(related_name='dislike', to='userUnit.CdUser'),
        ),
        migrations.AlterField(
            model_name='duan',
            name='liker',
            field=models.ManyToManyField(related_name='like', to='userUnit.CdUser'),
        ),
    ]
