# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0007_auto_20160517_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='duan',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
