# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0007_duanmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanmessage',
            name='isNew',
            field=models.BooleanField(default=True),
        ),
    ]
