# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0008_duanmessage_isnew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
