# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudUnit', '0009_auto_20160524_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='duanlabel',
            name='colour',
            field=models.IntegerField(default=0),
        ),
    ]
