# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import userUnit.models


class Migration(migrations.Migration):

    dependencies = [
        ('userUnit', '0002_cduser_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='cduser',
            name='portrait',
            field=models.ImageField(default='uploadFiles/User/defaultImage/1.jpg', upload_to=userUnit.models.userDirectoryPath),
        ),
    ]
