# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userUnit', '0006_auto_20160516_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='cduser',
            name='newsCount',
            field=models.IntegerField(default=0),
        ),
    ]
